# Generated by Django 5.2.17 on 2026-09-07 15:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Это поле не может состоять только из пробелов.', regex='.*\\S.*')], verbose_name='имя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлен')),
            ],
            options={
                'verbose_name': 'участник семьи',
                'verbose_name_plural': 'участники семьи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChoreSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Это поле не может состоять только из пробелов.', regex='.*\\S.*')], verbose_name='название')),
                ('recurrence', models.CharField(choices=[('one-time', 'Без повтора'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='one-time', max_length=10, verbose_name='повторение')),
                ('next_due_at', models.DateTimeField(verbose_name='ближайший срок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chore_schedules', to='chores.familymember', verbose_name='ответственный')),
            ],
            options={
                'verbose_name': 'расписание дела',
                'verbose_name_plural': 'расписания дел',
                'ordering': ['next_due_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChoreOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(verbose_name='срок выполнения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='chores.choreschedule', verbose_name='расписание')),
            ],
            options={
                'verbose_name': 'экземпляр дела',
                'verbose_name_plural': 'экземпляры дел',
                'ordering': ['due_at'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'due_at'), name='unique_chore_occurrence_due_at')],
            },
        ),
    ]
